[workspace]
members = [
    "condition_numbers",
    "eigenvalues_partial_problem",
    "eigenvalues_problem",
    "grid_method",
    "heat_equation",
    "iterative_methods",
    "matrices",
    "projection_methods",
    "qr_decomposition"
]
resolver = "2"
