[package]
name = "optimization"
version = "0.1.0"
edition = "2021"

[dependencies]
finitediff = { version = "0.1", features = ["ndarray"] }
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16", features = ["openblas"] }
